apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-empire
spec:
  replicas: 5
  selector:
    matchLabels:
      app: genesis-empire
  template:
    metadata:
      labels:
        app: genesis-empire
    spec:
      containers:
      - name: empire-container
        image: yourdockerhub/genesis-empire:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: genesis-service
spec:
  type: LoadBalancer
  selector:
    app: genesis-empire
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
